name: Run Integration Tests

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: pip install pytest requests

      - name: Start server
        run: |
          python http_driver.py --port 5000 &
          echo $! > pid.txt
          sleep 2

      - name: Run tests
        run: pytest labgrid/test_supporttool_labgrid.py

      - name: Stop server
        if: always()
        run: kill $(cat pid.txt)
